### ISSUE TITLE
Suggestion: In Step 2, change "table view controller" to "view controller"

### ISSUE THREAD

**Issue by AmitaiB** [learn-co-curriculum/slapchat-add#4]
A table view controller does not seem to be the intention of the lab (see the grammar of Step 4). It also seems needlessly complicated to me...

**Comment by AnnJohn** [comment]
Thanks @AmitaiB for raising the issue. We're reviewing and updating all of our content and will get to all issues soon. Also as a suggestion, please look at open, existing issues to make sure that someone else hasn't raised an issue that's identical or extremely similar to yours. I believe there is already an issue open regarding changing table view controller to view controller, so if that is the case, then please comment in that existing issue and include any clarifying info that wasn't included in the already open issue. This will better help us keep things organized on our end and will help us get to resolving issues sooner. Thanks again for being so diligent with reviewing our curriculum!

**Comment by AmitaiB** [comment]
Will do!
